function(assign_source_group)
    foreach(_source IN ITEMS ${ARGN})
        if (IS_ABSOLUTE "${_source}")
            file(RELATIVE_PATH _source_rel "${CMAKE_CURRENT_SOURCE_DIR}" "${_source}")
        else()
            set(_source_rel "${_source}")
        endif()
        get_filename_component(_source_path "${_source_rel}" PATH)
        string(REPLACE "/" "\\" _source_path_msvc "${_source_path}")
        source_group("${_source_path_msvc}" FILES "${_source}")
    endforeach()
endfunction(assign_source_group)


function(GET_OS OS)
    if (${CMAKE_SYSTEM_NAME} MATCHES "Windows")
        set(WIN32 TRUE PARENT_SCOPE)
        set(OS Win32 PARENT_SCOPE)
    elseif (${CMAKE_SYSTEM_NAME} MATCHES "Linux")
        set(LINUX TRUE PARENT_SCOPE)
        set(OS LINUX PARENT_SCOPE)
    elseif (${CMAKE_SYSTEM_NAME} MATCHES "Darwin")
        set(OSX TRUE PARENT_SCOPE)
        set(OS OSX PARENT_SCOPE)
    endif()
endfunction(GET_OS)